### ISSUE TITLE
-c option without mgmt_ip definitions doesn't populate /etc/hosts

### ISSUE THREAD

**Issue by rdarbha** [CumulusNetworks/topology_converter#63] opened 2017-06-29 13:20 UTC
When running the -c option, the /etc/hosts file isn't populated unless all the following criteria are met:
1. mgmt_ip is defined on all network nodes
2. oob-mgmt-server is defined as an ode
3. mgmt_ip of oob-mgmt-server is in same subnet as mgmt_ip of network nodes

Relevant code that needs to be edited:
Vagrantfile
```
    device.vm.provision "file", source: "./helper_scripts/auto_mgmt_network/dhcpd.conf", destination: "~/dhcpd.conf"
    device.vm.provision "file", source: "./helper_scripts/auto_mgmt_network/dhcpd.hosts", destination: "~/dhcpd.hosts"
    device.vm.provision "file", source: "./helper_scripts/auto_mgmt_network/hosts", destination: "~/hosts"
    device.vm.provision "file", source: "./helper_scripts/auto_mgmt_network/ansible_hostfile", destination: "~/ansible_hostfile"
    device.vm.provision "file", source: "./helper_scripts/auto_mgmt_network/ztp_oob.sh", destination: "~/ztp_oob.sh"

    # Run the Config specified in the Node Attributes
    device.vm.provision :shell , privileged: false, :inline => 'echo "$(whoami)" > /tmp/normal_user'
    device.vm.provision :shell , path: "./helper_scripts/auto_mgmt_network/OOB_Server_Config_auto_mgmt.sh"
```

helper_scripts/auto_mgmt_network/OOB_Server_Config_auto_mgmt.sh
```
echo " ### Setting Up DHCP ###"
mv /home/$username/dhcpd.conf /etc/dhcp/dhcpd.conf
mv /home/$username/dhcpd.hosts /etc/dhcp/dhcpd.hosts
chmod 755 -R /etc/dhcp/*
systemctl restart isc-dhcp-server
```

**Comment by ericpulvino** [comment] 2017-07-28 02:01
This is effectively a duplicate of Issue #67 . Closing this one to work on #67

**Closed by ericpulvino** 2017-07-28 02:01 UTC
Labels: duplicate
