### ISSUE TITLE
coreOS nic type needs to be not virtio

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#26] opened 2016-10-12 14:17 UTC
for my servers to get reachability to work I needed to change virtio to this

`      vbox.customize ["modifyvm", :id, "--nictype1", "82545EM"]`

**Comment by ericpulvino** [comment] 2016-10-14 02:25
What was the specific issue that forced the change? Virtio support appears to be present in the coreos kernel so normal host behavior should ensue, however if you're bonding, yes you'll run into problems.

**Comment by screech** [comment] 2016-10-14 02:43
@sean, what Eric said .. what was the issue
@eric .. what is the bonding issue ?

**Comment by seanx820** [comment] 2016-10-14 02:46
Just put an IP address on both sides and try to ping. Didn't work until I change NIC driver. Literally just put a /24 on both sides and try with virtio, no dice. Also eventually I will be bonding.

**Comment by seanx820** [comment] 2016-10-14 02:47
Cumulus VX <-> CoreOS

**Comment by ericpulvino** [comment] 2016-10-14 03:05
@seanx820 Seems to ping without issues for me.

`
core@coreos ~ $ ip addr show eth2
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 44:38:39:00:00:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::4638:39ff:fe00:8/64 scope link 
       valid_lft forever preferred_lft forever


root@leaf1:/home/vagrant# ip addr add 192.168.1.2/24 dev swp1
root@leaf1:/home/vagrant# ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=1.15 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=0.721 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=0.591 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=64 time=0.710 ms
^C
--- 192.168.1.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3001ms
rtt min/avg/max/mdev = 0.591/0.794/1.156/0.216 ms
`

Cannot reproduce.

@screech The virtio driver that ships in most modern distros cannot report link speed which means that attempts to use it in LACP bonded interfaces will fail because the bonding driver is unable to determine link speed to report to the far side. Cumulus has patched the virtio driver and fixed this but it has not reached most distros yet.

**Comment by seanx820** [comment] 2016-10-14 14:02
@ericpulvino why would we make it virtio if we usually use bonding on hosts?  Maybe its an OSX + VBox issue with virtio... I can look later but need to get work done for customer.

**Comment by seanx820** [comment] 2016-10-14 14:29
@ericpulvino just remember I am on vagrant 1.8.6... what version did you try it on?

**Comment by screech** [comment] 2016-10-16 00:35
Vagrant should not matter, coreos version will matter. virtio cannot be
this broken, but the fact that you only changed the driver is strange. Did
you see the link up when the ping failed ? and any driver errors ?

**Comment by seanx820** [comment] 2016-10-17 19:23
core@server01 ~ $ uname -a
Linux server01 4.7.3-coreos #1 SMP Thu Oct 6 02:22:48 UTC 2016 x86_64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz GenuineIntel GNU/Linux

**Comment by ericpulvino** [comment] 2016-10-27 16:48
Closing -- can't reproduce.

**Closed by ericpulvino** 2016-10-27 16:48 UTC
